### ISSUE TITLE
HLS stream not compatible with Chromecast

### ISSUE THREAD

**Issue by San-Jeevan** [shogo4405/lf.swift#141]
Seems chromecast downloads the m3u8 file then just aborts.
Anyone else tested the HLS stream with chromecast?

**Comment by San-Jeevan** [comment]
it appear lf doesnt send CORS headers.

```
HTTP/1.1 200 OK
Content-Type: application/x-mpegURL
Connection: close

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:110
#EXT-X-TARGETDURATION:2
#EXTINF:2.00113068599603,
183489.ts
#EXTINF:2.00095889600925,
183491.ts
#EXTINF:2.00085038298857,
183493.ts
```

**Comment by San-Jeevan** [comment]
I found a fix to make this work with chromecast

add this to HTTPService.swift 

 ```
   func get(request:HTTPRequest, client:NetClient) {
        logger.verbose("\(request)")
        var response:HTTPResponse = HTTPResponse()
        response.headerFields["Connection"] = "close"
        
        //THIS IS NEW CODE YOU MUST ADD FOR CORS support
        response.headerFields["Access-Control-Allow-Headers"] = "*"
        response.headerFields["Access-Control-Expose-Headers"] = "*"
        response.headerFields["Access-Control-Allow-Methods"] = "GET, HEAD, OPTIONS"
        response.headerFields["Access-Control-Allow-Origin"] = "*"
```

**Comment by San-Jeevan** [comment]
@shogo4405

**Comment by shogo4405** [comment]
@San-Jeevan 
Thank u! I fixed it. I have no a chromecast :(

**Comment by quanlv9695** [comment]
@San-Jeevan 
I still can't play it directly on chromecast.
Here is my code:

 ```
let url = URL(string: "http://xxx.xxx.x.xxx:8081/chromecast/playlist.m3u8")
        guard let mediaURL = url else {
            print("invalid mediaURL")
            return
        }

       let mediaInfoBuilder = GCKMediaInformationBuilder(contentURL: mediaURL)
       
       mediaInfoBuilder.contentID = "http://xxx.xxx.x.xxx:8081/chromecast/playlist.m3u8"
       mediaInfoBuilder.streamType = GCKMediaStreamType.none
       mediaInfoBuilder.contentType = "application/x-mpegURL"
       mediaInfoBuilder.hlsSegmentFormat = .TS
       mediaInfoBuilder.hlsVideoSegmentFormat = .MPEG2_TS
       mediaInfoBuilder.streamDuration = .infinity
       let metadata = GCKMediaMetadata()
       mediaInfoBuilder.metadata = metadata
       mediaInformation = mediaInfoBuilder.build()
       guard let mediaInfo = mediaInformation else {
           print("invalid mediaInformation")
           return
       }
       
       if let request = sessionManager?.currentSession?.remoteMediaClient?.loadMedia(mediaInfo) {
           request.delegate = self
       }
```

The error returned from chromecast is:
_Error Domain=com.google.cast.GCKError Code=30 "Media failed to load" UserInfo={NSLocalizedDescription=Media failed to load, gck_detailed_error_code=104}_
